import type { MolecularCandidate } from "./api-client";
import type { Lang } from "./i18n";

export const MOCK_CANDIDATES: MolecularCandidate[] = [
  {
    id: "BRM-001",
    composition: "Fucoidan-Quercetin Hybrid",
    source: "hybrid",
    score: 97.4,
    patentability: "High",
    dockingScore: -9.82,
    efficacyProfile: { antiInflammatory: 95, antioxidant: 88, antimicrobial: 72, antitumor: 91, neuroprotection: 68, immunoModulation: 84 },
    admet: { absorption: 88, distribution: 79, metabolism: 74, excretion: 83, toxicity: 12 },
  },
  {
    id: "BRM-002",
    composition: "Eckol-Kaempferol Complex",
    source: "hybrid",
    score: 94.1,
    patentability: "High",
    dockingScore: -9.41,
    efficacyProfile: { antiInflammatory: 89, antioxidant: 94, antimicrobial: 65, antitumor: 78, neuroprotection: 82, immunoModulation: 71 },
    admet: { absorption: 82, distribution: 85, metabolism: 69, excretion: 78, toxicity: 18 },
  },
  {
    id: "TRR-003",
    composition: "Curcumin-Resveratrol Nano",
    source: "terrestrial",
    score: 91.8,
    patentability: "Medium",
    dockingScore: -8.97,
    efficacyProfile: { antiInflammatory: 92, antioxidant: 96, antimicrobial: 58, antitumor: 85, neuroprotection: 77, immunoModulation: 89 },
    admet: { absorption: 74, distribution: 71, metabolism: 88, excretion: 81, toxicity: 8 },
  },
  {
    id: "MRN-004",
    composition: "Phlorotannin-Spirulina Derivative",
    source: "marine",
    score: 89.3,
    patentability: "High",
    dockingScore: -8.74,
    efficacyProfile: { antiInflammatory: 76, antioxidant: 82, antimicrobial: 91, antitumor: 69, neuroprotection: 74, immunoModulation: 95 },
    admet: { absorption: 91, distribution: 77, metabolism: 72, excretion: 85, toxicity: 14 },
  },
  {
    id: "BRM-005",
    composition: "Astaxanthin-Epigallocatechin",
    source: "hybrid",
    score: 87.6,
    patentability: "High",
    dockingScore: -8.55,
    efficacyProfile: { antiInflammatory: 83, antioxidant: 98, antimicrobial: 61, antitumor: 74, neuroprotection: 91, immunoModulation: 78 },
    admet: { absorption: 79, distribution: 82, metabolism: 76, excretion: 74, toxicity: 9 },
  },
  {
    id: "TRR-006",
    composition: "Berberine-Agar Oligosaccharide",
    source: "hybrid",
    score: 85.2,
    patentability: "Medium",
    dockingScore: -8.31,
    efficacyProfile: { antiInflammatory: 78, antioxidant: 71, antimicrobial: 88, antitumor: 82, neuroprotection: 65, immunoModulation: 73 },
    admet: { absorption: 85, distribution: 68, metabolism: 81, excretion: 77, toxicity: 21 },
  },
  {
    id: "MRN-007",
    composition: "Carrageenan-Luteolin Conjugate",
    source: "marine",
    score: 83.7,
    patentability: "Medium",
    dockingScore: -8.14,
    efficacyProfile: { antiInflammatory: 87, antioxidant: 74, antimicrobial: 69, antitumor: 71, neuroprotection: 58, immunoModulation: 88 },
    admet: { absorption: 76, distribution: 74, metabolism: 79, excretion: 82, toxicity: 17 },
  },
  {
    id: "BRM-008",
    composition: "Sargassum-Ginsenoside RG3",
    source: "hybrid",
    score: 81.9,
    patentability: "High",
    dockingScore: -7.98,
    efficacyProfile: { antiInflammatory: 74, antioxidant: 79, antimicrobial: 55, antitumor: 93, neuroprotection: 86, immunoModulation: 82 },
    admet: { absorption: 81, distribution: 86, metabolism: 74, excretion: 79, toxicity: 11 },
  },
  {
    id: "TRR-009",
    composition: "Silymarin-Chitosan Nanoparticle",
    source: "hybrid",
    score: 79.4,
    patentability: "Low",
    dockingScore: -7.76,
    efficacyProfile: { antiInflammatory: 81, antioxidant: 85, antimicrobial: 62, antitumor: 67, neuroprotection: 72, immunoModulation: 69 },
    admet: { absorption: 88, distribution: 73, metabolism: 82, excretion: 75, toxicity: 15 },
  },
  {
    id: "MRN-010",
    composition: "Undaria-Hesperidin Scaffold",
    source: "marine",
    score: 77.8,
    patentability: "Medium",
    dockingScore: -7.54,
    efficacyProfile: { antiInflammatory: 71, antioxidant: 76, antimicrobial: 74, antitumor: 65, neuroprotection: 69, immunoModulation: 91 },
    admet: { absorption: 77, distribution: 79, metabolism: 71, excretion: 83, toxicity: 19 },
  },
];

export const getSimulationLogs = (lang: Lang) => {
  const templates: Record<Lang, ((i: number) => string)[]> = {
    en: [
      (i) => `Iteration #${i.toLocaleString()} — Molecular graph traversal complete`,
      (i) => `Iteration #${i.toLocaleString()} — Docking simulation: AutoDock Vina score computed`,
      (i) => `Iteration #${i.toLocaleString()} — ADMET prediction pass rate: ${(Math.random() * 20 + 75).toFixed(1)}%`,
      (i) => `Iteration #${i.toLocaleString()} — Novel scaffold detected in marine terpene family`,
      (i) => `Iteration #${i.toLocaleString()} — Synergy matrix updated (Terrestrial × Marine)`,
      (i) => `Iteration #${i.toLocaleString()} — Molecular Docking Success: ${(Math.random() * 15 + 75).toFixed(0)}%`,
      (i) => `Iteration #${i.toLocaleString()} — Blood-brain barrier permeability: estimated`,
      (i) => `Iteration #${i.toLocaleString()} — CYP450 metabolism check: 3 hits flagged`,
      (i) => `Iteration #${i.toLocaleString()} — Toxicity filter: ${Math.floor(Math.random() * 50 + 20)} candidates pruned`,
      (i) => `Iteration #${i.toLocaleString()} — Convergence delta: ${(Math.random() * 0.002).toFixed(5)}`,
    ],
    ko: [
      (i) => `반복 #${i.toLocaleString()} — 분자 그래프 탐색 완료`,
      (i) => `반복 #${i.toLocaleString()} — 도킹 시뮬레이션: AutoDock Vina 점수 산출`,
      (i) => `반복 #${i.toLocaleString()} — ADMET 예측 통과율: ${(Math.random() * 20 + 75).toFixed(1)}%`,
      (i) => `반복 #${i.toLocaleString()} — 해양 테르펜 계열에서 신규 스캐폴드 탐지`,
      (i) => `반복 #${i.toLocaleString()} — 시너지 매트릭스 갱신 (육상 × 해양)`,
      (i) => `반복 #${i.toLocaleString()} — 분자 도킹 성공률: ${(Math.random() * 15 + 75).toFixed(0)}%`,
      (i) => `반복 #${i.toLocaleString()} — 혈뇌장벽 투과성 추정 완료`,
      (i) => `반복 #${i.toLocaleString()} — CYP450 대사 검토: 3개 후보 플래그 처리`,
      (i) => `반복 #${i.toLocaleString()} — 독성 필터: ${Math.floor(Math.random() * 50 + 20)}개 후보 제거`,
      (i) => `반복 #${i.toLocaleString()} — 수렴 델타: ${(Math.random() * 0.002).toFixed(5)}`,
    ],
  };
  return templates[lang];
};
